name = "VicsekModel"
uuid = "98ddeb29-8e3e-4511-b248-9704d49e4601"
authors = ["Masashi Shiraishi <shiraishi.mu@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
